"""Part (a): margin objective + L2-to-prior, and the identifiability re-check.

Key correction over the first attempt: cosine-to-w* only means something when the
labels are generated by the model the objective is the MLE for. MRR saturates and
under-identifies theta regardless; the margin (log-softmax) + L2 objective is the
Plackett-Luce MLE, so on softmax-generated labels it recovers the w* DIRECTION.
We verify both the jump and that out-of-fold ranking is preserved.
"""
import numpy as np
import pandas as pd

from ranker import Case, default_registry, theta_keys
from ranker._util import variant_key
from ranker.optimize import (cv_optimize, make_margin_objective, metric_getter,
                             optimize_theta)
from verify_layer3 import (W_STAR_VEC, _causal, _filler, _subvec, _trap, cosine,
                           KEYS, REG)

TAU = 40.0


def stochastic_case(cid, rng, n_filler=12):
    pos0 = 1000
    rows = [_causal(rng, pos0), _trap(rng, pos0 + 7)]
    rows += [_filler(rng, pos0 + 14 + 7 * i) for i in range(n_filler)]
    subs = np.array([_subvec(r) for r in rows])
    logits = (subs @ W_STAR_VEC) / TAU
    p = np.exp(logits - logits.max()); p /= p.sum()
    ci = int(rng.choice(len(rows), p=p))            # Plackett-Luce / softmax label
    cr = rows[ci]
    return Case(cid, pd.DataFrame(rows),
                [variant_key(cr["chrom"], cr["pos"], cr["ref"], cr["alt"])])


def main():
    cases = [stochastic_case(f"S{i}", np.random.default_rng(i)) for i in range(150)]

    # MRR-trained (saturating objective) -- repeated seeds to show instability
    mrr_vecs = []
    for sd in (0, 1, 2):
        b, _, _ = optimize_theta(cases, REG, n_trials=200, backend="cma", seed=sd)
        mrr_vecs.append(np.array([b[k] for k in KEYS]))
    cos_mrr = np.mean([cosine(v, W_STAR_VEC) for v in mrr_vecs])
    spread_mrr = np.mean([1 - cosine(mrr_vecs[i], mrr_vecs[j])
                          for i in range(3) for j in range(i + 1, 3)])

    # margin + L2 -> identified direction; repeated seeds to show stability
    obj = make_margin_objective(REG, level="variant", l2=1e-2)
    mar_vecs = []
    for sd in (0, 1, 2):
        b, _, _ = optimize_theta(cases, REG, objective=obj, n_trials=300,
                                 backend="cma", seed=sd)
        mar_vecs.append(np.array([b[k] for k in KEYS]))
    cos_mar = np.mean([cosine(v, W_STAR_VEC) for v in mar_vecs])
    spread_mar = np.mean([1 - cosine(mar_vecs[i], mar_vecs[j])
                          for i in range(3) for j in range(i + 1, 3)])

    rep_m = cv_optimize(cases, REG, objective=obj, n_folds=5, seed=0,
                        n_trials=150, backend="cma", levels=("variant",))
    oof_m = rep_m["oof_tuned"]["variant"]
    oof_b = rep_m["oof_baseline"]["variant"]

    bt = mar_vecs[0]
    print(f"[data] {len(cases)} softmax-labelled cases (tau={TAU})")
    print(f"[recovery] cosine(theta, w*):   MRR={cos_mrr:.3f}   margin+L2={cos_mar:.3f}")
    print(f"[stability] cross-seed 1-cos spread:  MRR={spread_mrr:.3f}   margin+L2={spread_mar:.3f}")
    print(f"[ranking ] OOF variant MRR  baseline={oof_b['MRR']:.3f}  tuned={oof_m['MRR']:.3f}  "
          f"recall@1 {oof_b['recall@1']:.3f}->{oof_m['recall@1']:.3f}")
    print("[theta_margin]", {k: round(bt[i], 2) for i, k in enumerate(KEYS)})
    print("[w*]          ", {k: round(W_STAR_VEC[i], 2) for i, k in enumerate(KEYS)})

    assert cos_mar > cos_mrr + 0.05, (cos_mrr, cos_mar)
    assert cos_mar > 0.9
    assert spread_mar < spread_mrr            # margin theta is more stable across seeds
    assert oof_m["MRR"] > oof_b["MRR"]        # ranking still improves OOF
    print("\nVERIFIED: margin+L2 makes cosine(theta,w*) jump AND theta stable across "
          "seeds, while OOF ranking still beats baseline.")


if __name__ == "__main__":
    main()
